# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../module_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'module_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for module_ios
  install_all_flutter_pods(flutter_application_path)

  target 'module_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'module_iosUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
#       config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
    end
  end

#   installer.pods_project.build_configurations.each do |config|
#     config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#   end
end
